config/routes.rb
Rails.application.routes.draw do

	resources :players
	root 'players#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
	before_action :find_player, only: [:show, :edit, :update, :destroy]

def index
	@players = Player.all
end

def new
	@player = Player.new
end

def create
 @player = Player.new(player_params)
 if @player.save
 	redirect_to player_path(@player)
 end
end

def show

end


def edit

end

def update
 if @player.update(player_params)
 	redirect_to player_path(@player)
 end
end

def destroy
	@player.destroy
	redirect_to root_path
end

private

def find_player
	@player = Player.find(params[:id])
end

def player_params
	params.require(:player).permit(:nickname, :rank, :charisma, :wisdom)
end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/_form.html.erb
<%= form_for @player do |p| %>

<%= p.label :nickname %> <br>
<%= p.text_field :nickname %> <br>
<%= p.label :rank %> <br>
<%= p.text_field :rank %> <br>
<%= p.label :charisma %> <br>
<%= p.text_field :charisma %> <br>
<%= p.label :wisdom %> <br>
<%= p.text_field :wisdom %> <br>
<%= p.submit 'Create' %>
<% end %>

app/views/players/edit.html.erb
<%= render 'form' %>

app/views/players/index.html.erb
<% @players.each do |playerT| %>
<%= playerT.nickname %> <br>
<%= link_to 'Show', player_path(playerT.id)%> <br>
<% end %>

<%= link_to 'Add new player', new_player_path%> <br>

app/views/players/new.html.erb
<%= render 'form' %>

app/views/players/show.html.erb
<h2> <%= @player.nickname %></h2>
<h2> <%= @player.rank %></h2>
<h2> <%= @player.charisma %></h2>
<h2> <%= @player.wisdom %></h2>

<%= link_to 'Back', root_path %> <br>
<%= link_to 'Edit', edit_player_path(@player.id) %> <br>
<%= link_to 'Delete', player_path(@player.id), method: :delete, data: {confirm: "Are you sure?"}%>